name: uaepass
description: UAE PASS service allows using a mobile device as a secure form of identification. UAE PASS automates and simplifies managing digital identity in mobile devices for users.
version: 0.0.5
repository: https://github.com/Alkhajeh/Flutter-UAEPass
issue_tracker: https://github.com/Alkhajeh/Flutter-UAEPass/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  http: ^0.13.5
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.uaepass
        pluginClass: UaepassPlugin
      ios:
        pluginClass: UaepassPlugin

  assets:
    - images/
